---
title: "Mapa_Lima"
author: "Gianfranco Raúl Romero Sucapuca"
date: "2024-05-03"
output: html_document
---

```{r}
library(rio)
```


```{r}
library(sf)
mapa = sf::read_sf("Distrital INEI 2023 geogpsperu SuyoPomalia.shp")
```

```{r}
library(dplyr)
mapa_lima = mapa %>% filter(PROVINCIA == "LIMA")
```

```{r}
library(ggplot2)
```

```{r}
data_lima = import("data_lima.xlsx")
```

```{r}
dat_map = merge(x = mapa_lima, y = data_lima, by = c("UBIGEO", "DISTRITO"))
```

```{r}
LV <- subset(dat_map, DISTRITO == "LA VICTORIA")
```

```{r}
RP_W <- subset(dat_map, ALCALDE_RP == 1)
RP_L <- subset(dat_map, ALCALDE_RP == 0)
```


```{r}
modelo1=lm(VOTOS_LM~IDH,data=dat_map)
```

```{r, warning=FALSE, message=FALSE}
library(ggplot2)

ggplot(dat_map,aes(x = IDH, y = VOTOS_LM)) + 
  geom_point() + 
  geom_smooth(method = "lm", se=FALSE) +
  stat_cor(aes(label = paste(..rr.label.., ..p.label.., sep = "*`,`~")),
           label.y= 59, label.x = 0.65, vjust = 1, hjust = 1.1, size = 5) +
  labs(title = "El IDH y los votos para RLA en los distritos de Lima metropolitana",
       subtitle = 'Elecciones Regionales y Municipales de 2022',
       x = "Índice de Desarrollo Humano (2019)",
       y = "% de votos para RLA (Alcaldía de Lima)",
       caption = "Fuente: ONPE & PNUD. Elaboración propia.")
```




```{r}
idh_rp <- ggplot(dat_map) +
  geom_sf(aes(fill = IDH), color = "black") +
  geom_sf(data = RP_L, color = "black", fill = "gray") +
  geom_sf(data = LV, color = "darkblue", linewidth = 0.9, fill = NA) +
  geom_text(data = data.frame(x = -77.015, y = -12.066, label = "La Victoria"), aes(x = x, y = y, label = label), color = "black", size = 3) +
  scale_fill_gradient(
    low = "#FF0000",
    high = "#00EA2B",
    guide = guide_colorbar(title = "Índice de Desarrollo Humano")) +
  coord_sf(xlim = c(-77.12, -76.7), ylim = c(-12.17, -11.95), expand = FALSE) +
  labs(title = "Índice de Desarrollo Humano en Lima metropolitana",
       subtitle = 'Distritos con un alcalde de Renovación Popular',
       caption = "Fuente: PNUD (2019). Elaboración propia.",
       x = " ",
       y = " ")

idh_rp
```

```{r}
ggsave("idh_rp.png")
```





```{r}
ggplot(dat_map) +
  geom_sf(aes(fill = H_ALTO), color = "black") +
  geom_sf(data = RP_L, color = "black", fill = "gray") +
  geom_sf(data = LV, color = "darkblue", linewidth = 0.9, fill = NA) +
  geom_text(data = data.frame(x = -77.015, y = -12.066, label = "La Victoria"), aes(x = x, y = y, label = label), color = "black", size = 3) +
  scale_fill_gradient(
    low = "white",
    high = "purple",
    limits = c(0, 100),
    guide = guide_colorbar(title = "% de hogares")) +
  coord_sf(xlim = c(-77.12, -76.7), ylim = c(-12.17, -11.95), expand = FALSE) +
  labs(title = "Porcentaje de hogares de ingreso alto en Lima metropolitana",
       subtitle = 'Distritos con un alcalde de Renovación Popular',
       caption = "Fuente: INEI (2022). Elaboración propia.",
       x = " ",
       y = " ")
```

```{r}
ggplot(dat_map) +
  geom_sf(aes(fill = H_MDALTO), color = "black") +
  geom_sf(data = RP_L, color = "black", fill = "gray") +
  geom_sf(data = LV, color = "darkblue", linewidth = 0.9, fill = NA) +
  geom_text(data = data.frame(x = -77.015, y = -12.066, label = "La Victoria"), aes(x = x, y = y, label = label), color = "black", size = 3) +
  scale_fill_gradient(
    low = "white",
    high = "yellow",
    limits = c(0, 100),
    guide = guide_colorbar(title = "% de hogares")) +
  coord_sf(xlim = c(-77.12, -76.7), ylim = c(-12.17, -11.95), expand = FALSE) +
  labs(title = "Porcentaje de hogares de ingreso medio alto en Lima metropolitana",
       subtitle = 'Distritos con un alcalde de Renovación Popular',
       caption = "Fuente: INEI (2022). Elaboración propia.",
       x = " ",
       y = " ")
```

```{r}
ggplot(dat_map) +
  geom_sf(aes(fill = H_MEDIO), color = "black") +
  geom_sf(data = RP_L, color = "black", fill = "gray") +
  geom_sf(data = LV, color = "darkblue", linewidth = 0.9, fill = NA) +
  geom_text(data = data.frame(x = -77.015, y = -12.066, label = "La Victoria"), aes(x = x, y = y, label = label), color = "black", size = 3) +
  scale_fill_gradient(
    low = "white",
    high = "#FF6100",
    limits = c(0, 100),
    guide = guide_colorbar(title = "% de hogares")) +
  coord_sf(xlim = c(-77.12, -76.7), ylim = c(-12.17, -11.95), expand = FALSE) +
  labs(title = "Porcentaje de hogares de ingreso medio en Lima metropolitana",
       subtitle = 'Distritos con un alcalde de Renovación Popular',
       caption = "Fuente: INEI (2022). Elaboración propia.",
       x = " ",
       y = " ")
```






```{r}
ggplot(dat_map) +
  geom_sf(aes(fill = ALCALDE_RP), color = "black") +
  geom_sf(data = LV, color = "purple", linewidth = 1, fill = NA) +
  scale_fill_manual(values=c("lightgray","#4BBADE")) +
  coord_sf(xlim = c(-77.12, -76.7), ylim = c(-12.17,-11.95), expand = FALSE)
```

```{r}
ggplot(dat_map) +
  geom_sf(aes(fill = VOTOS_DIS), color = "black") +
  scale_fill_continuous(low = "white", high = "#4BBADE") +
  coord_sf(xlim = c(-77.1, -76.7), ylim = c(-12.2,-11.9), expand = FALSE)
```

```{r}
dat_map$ALCALDE_RP = as.factor(dat_map$ALCALDE_RP)
```

```{r}

```










# IDH Lima metropolitana

```{r}
idh_lm <- ggplot(dat_map) +
  geom_sf(aes(fill = IDH), color = "black", linewidth = 0) +
  scale_fill_viridis_b(name = "Índice de Desarrollo Humano",
                       limits = c(0.50, 0.85),
                       breaks = seq(0.50, 0.85,0.5),
                       )  +
  labs(title = "Índice de Desarrollo Humano en Lima metropolitana",
       subtitle = ' ',
       caption = "Fuente: PNUD (2019). Elaboración propia.",
       x = " ",
       y = " ") +
  theme(axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        panel.background = element_rect(fill = "white"),
        panel.border = element_rect(colour = "black", fill = NA)) +
  guides(colour = )

idh_lm
```


```{r}
ggsave("idh_lm.png")
```










